version: '3.9'
services:
  database:
    image: mysql:8
    command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: database
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=docker
  app:
    build: .
    container_name: app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    links:
      - database
    depends_on:
      - database
    command: sh -c "/wait; npm ci; npx prisma migrate dev; npx prisma db seed; npm run dev"
    environment:
      - WAIT_HOST=database:3306
      - WAIT_HOST_TIMEOUT=300
      - WAIT_HOST_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=15