import './providers/HashProvider/index'
import '@modules/authentication/providers'
import '@modules/admin/costumer/providers'
import '@modules/admin/car/providers'
import '@modules/admin/rent/providers'
